apiVersion: apps/v1
kind: Deployment
metadata:
  name: vs-fe
  labels:
    app: vs-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vs-fe
  template:
    metadata:
      labels:
        app: vs-fe
    spec:
      containers:
        - name: vs-fe
          image: sujiththirumalaisamy/vector-shift-fe:1369fecf7e635ebbae6f4f97a8376bcd39d66a8a
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
