apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - port: 80
      targetPort: 4499
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vs-fe-route
  namespace: default

spec:
  parentRefs:
  - name: gateway-api
    sectionName: http
    kind: Gateway
  - name: gateway-api
    sectionName: https
    kind: Gateway

  hostnames:
  - wisecow.isujith.dev

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: wisecow-service
      port: 80
      weight: 1
